### ISSUE TITLE
Suggestion: Creative Vending Recipe Change

### ISSUE THREAD

**Issue by LarcekGiglamesh** [ArtpokeBr/ArtPack#13]
based on: 3.2.7

i'd like to suggest to change the Recipe of the Creative Vending Upgrade to use AE2 materials counterparts instead of the existing RS materials. for once, it's harder to craft those counterparts, but additionally, since RS is known to perform worse on servers, we have these mods (RefinedStorage, RebornStorage) disabled on our Server so the recipe fails. 

Workarounds are possible in case you see no need to.

**Comment by ArtpokeBr** [comment]
I'll take a look at that when possible, thx for informing me :)
