### ISSUE TITLE
Villages just aren't there

### ISSUE THREAD

**Issue by Uchiwars** [ArtpokeBr/ArtPack#14]
**Modpack version 3.2.7**

There are roads and 2 Sage villagers but nothing else, if intended ok but if not it needs a fix :)

![image](https://user-images.githubusercontent.com/54306921/99839449-00cf1b00-2b6b-11eb-9260-c61ceb82e51f.png)

**Comment by LarcekGiglamesh** [comment]
Modpack Version: 3.2.7

Might be related, but RTG Config Subfolder has Villages enabled for only a selected few Biomes.

**Comment by ArtpokeBr** [comment]
I've tried to fix this nonStop when implementing this world generation to the Pack, even adding Mods that specifically add something to villages to maybe force them to load correctly but It didn't work at all :/
