### ISSUE TITLE
Immersive Engineering Metal Press rear/input conveyor glitch

### ISSUE THREAD

**Issue by Superc80** [ArtpokeBr/ArtPack#15]
When you destroy a metal press (this has only been tested by breaking the front/output conveyor first), the rear/input conveyor loses the animated part of its texture and said part changes to a purple and black checkerboard pattern and it loses all functionality as a conveyor and cannot be used to create the metal press multi-block structure again, the item is also renamed to tile.immersiveengineering.conveyor..name , please fix this bug if you can.

**Comment by ArtpokeBr** [comment]
What? this is a serious bug that Didn't know about! well, I can't do much right now since CurseForge is on Read Only, But I'll try to maybe update immersive or something ASAP.
