### ISSUE TITLE
ContentTweaker - Runic Altar - Divination Dust - Recipe Issue

### ISSUE THREAD

**Issue by JGlennT** [ArtpokeBr/ArtPack#16]
Recipe will not craft.  The Recipe for Divination Dust requires 2 White Magic Dust, 2 Dark Magic Dust and 2 Aromatic Lump.  The recipe has these stacked but the Runic Altar treats them as single items instead of stacked (see other recipes for how multiples of the same items are treated) and the recipe cannot be crafted.  Screenshots of both the recipe and how the items appear on the Runic Altar are attached.  If the recipe is changed to unstack the items it should work.
![2020-11-29_19 28 22](https://user-images.githubusercontent.com/75228517/100558016-77120280-327a-11eb-817e-2b765b4c736e.png)
![2020-11-29_19 28 49](https://user-images.githubusercontent.com/75228517/100558020-7a0cf300-327a-11eb-8f74-71e8d96cc8ae.png)

**Comment by JGlennT** [comment]
Update - I overthought this, Even though the Recipe says 2 items needed, the Runic Altar will craft this with only 1 item as it does not support stacks.

**Comment by ArtpokeBr** [comment]
So the recipe works? it is weird, in the Crafttweaker scripts I can use Stacks of items haha, but Ok! Will work on it.

**Comment by JGlennT** [comment]
Yes recipe works both only requires 1 each of the items indicated as stacks of 2.  Thanks for a great pack and support.

**Comment by ArtpokeBr** [comment]
Ok, at least the recipe still works haha, but I will fix it when possible, right now curse is unstable due the transition to Overwolf, so It will be fixed when possible :)
