### ISSUE TITLE
Can't craft ultimate ingot

### ISSUE THREAD

**Issue by allyworoniuk** [ArtpokeBr/ArtPack#17]
![image](https://user-images.githubusercontent.com/37962459/100806855-10115c80-33e6-11eb-8392-14a71e734d1e.png)

![image](https://user-images.githubusercontent.com/37962459/100806563-85c8f880-33e5-11eb-9253-9561602a58f0.png)

I used the direct insert for the ingots, to ensure every ingot is present, the only conflict I can imagine is that the original recipe calls for an unstable ingot, which I used a stable-unstable ingot (since you literally can't use an unstable in this recipe.)

**Comment by ArtpokeBr** [comment]
Oh yeah, this is a know issue, will be fixed in the Next patch for sure! thx for reporting. ASAP I will be fixing it.

**Comment by allyworoniuk** [comment]
Oooh okay thanks :D

**Comment by allyworoniuk** [comment]
do you have an estimate when your next patch will be?

**Comment by ArtpokeBr** [comment]
Right now CurseForge's New launcher doesn't have the Export feature, so I can't update the pack =/
