### ISSUE TITLE
Construct's Armory

### ISSUE THREAD

**Issue by VF-Plays** [ArtpokeBr/ArtPack#19]
In the modpack, you need to use the tinkers but, the tinkers armors aren't avaible. I know that the mod is overpower, but I also know that you can nerf it to be more balanced. Is one mod that I miss. Can you put this mod in the modpack?

**Comment by ArtpokeBr** [comment]
Right now I can't update the pack beacuse of curse forge, but I'll take a look at this when possible, If I can clearly control the mod, I think I Can add it :p

**Comment by VF-Plays** [comment]
Thanks, I already saw the patch notes from the Curse, and I am aware that you can't update the modpack, but if you update this in the next patch I will be grateful.
