### ISSUE TITLE
Immersive Enginering Crusher is too slow

### ISSUE THREAD

**Issue by PrismaticHead00** [ArtpokeBr/ArtPack#22]
It is taking 10 minutes or more to process just one iron ore, is intended?

**Comment by PrismaticHead00** [comment]
On a test world, with infinity power, continue slow

**Comment by ArtpokeBr** [comment]
I didn't changed the Immersive Crusher :T maybe it is something with the Mod itself, I Didn't update the Mods recently beacuse the  Export feature still kinda buggy, but I'll take a look when possible.
