### ISSUE TITLE
Creative Mekanism Quests

### ISSUE THREAD

**Issue by LarcekGiglamesh** [ArtpokeBr/ArtPack#9]
hello there,

Version: 3.2.6

to keep it short, you need to toggle the "NBT Contain" option on the Quests for the "Creative Fluid Tank" and "Creative Gas Tank", since even crafting a Basic one will trigger the rewards, essentially breaking the Pack within Minutes. 

Mekanism has most of their Tile Entity data stored in NBT so Quests bases around Mekanism are known to work funky. 

Cheers

**Comment by ArtpokeBr** [comment]
Oh thx for reporting, it is crazy cause in recent updates I've actually enabled "NBT Match" on the quests but for some reason it doesn't get correct on the Update? I will make sure to verify again when working on the Next Update, but thx for reporting!

**Comment by ArtpokeBr** [comment]
I've already fixed here, All should be normal in the Next Patch.
